### Intuition:
- Considered Algorithms:
  - Linear Kernel
  - Cosine Similarity

* Word to Vector Algorithms:
  * TF-IDF Vectorizer
  * Count Vectorizer

# Importing required libraries

In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity

import warnings
warnings.filterwarnings("ignore")

### Loading Dataset

In [2]:
FILEPATH="../data/train/"

df = pd.read_csv(FILEPATH+"meta_data.csv")

In [3]:
df.head()

,title,meta_tags
0,Avatar,action adventure fantasy science fiction cultu...
1,Pirates of the Caribbean: At World's End,adventure fantasy action ocean drug abuse exot...
2,Spectre,action adventure crime spy based on novel secr...
3,The Dark Knight Rises,action crime drama thriller dc comic crime fig...
4,John Carter,action adventure science fiction based on nove...

In [4]:
df.isnull().sum()

title        0
meta_tags    0
dtype: int64

## Word to Vector

### TF-IDF Vectorizer

In [5]:
tf_idf_obj = TfidfVectorizer()
tfvt = tf_idf_obj.fit_transform(df['meta_tags'])

In [6]:
pd.DataFrame(tfvt.toarray(), columns=tf_idf_obj.get_feature_names_out())

,00,000,007,07am,10,100,1000,101,108,10th,...,zorro,zuckerberg,zula,zurich,zuzu,zyklon,γη,卧底肥妈,绝地奶霸,超级妈妈
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4799,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4801,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4802,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### CountVectorizer

In [7]:
cv_obj = CountVectorizer(analyzer='word', lowercase=True, stop_words='english')
cvt = cv_obj.fit_transform(df['meta_tags'])

In [8]:
pd.DataFrame(cvt.toarray(), columns=cv_obj.get_feature_names_out())

,00,000,007,07am,10,100,1000,101,108,10th,...,zorro,zuckerberg,zula,zurich,zuzu,zyklon,γη,卧底肥妈,绝地奶霸,超级妈妈
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4799,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4800,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4801,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4802,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Intuition:
#### We should use TF-IDF Vectorizer with Linear Kernel algorithm because:
- Linear Kernel is faster compared to cosine similarity algorithm but the trade-off is it does not perform L2 regularization. So, as a countermeasure we should use TF-IDF Vectorizer with Linear Kernel because TF-IDF performs L2 regularization.

#### We should use Count Vectorizer with Cosine Similarity algorithm because:
- Cosine similarity inherently perform L2 regularization, as a result it is slower as compared to Linear Kernel. On the other hand, Count Vectorizer do not perform L2 regularization. So, there two are good match for each other.

#### Linear Kernel with TF-IDF Vectorizer is always preferable when the dataset is huge. But in that case before performing TF-IDF vectorization we should perform more accurate meta-data composition to get good similarity scores.

# Method-1: using Linear Kernel with TfidfVectorizer

In [9]:
similarity_matrix_lk = linear_kernel(tfvt, tfvt)
similarity_matrix_lk

array([[1.        , 0.02058947, 0.01950882, ..., 0.02263226, 0.00418546,
        0.        ],
       [0.02058947, 1.        , 0.01987093, ..., 0.02899363, 0.        ,
        0.0059537 ],
       [0.01950882, 0.01987093, 1.        , ..., 0.01584896, 0.        ,
        0.        ],
       ...,
       [0.02263226, 0.02899363, 0.01584896, ..., 1.        , 0.02063465,
        0.03393385],
       [0.00418546, 0.        , 0.        , ..., 0.02063465, 1.        ,
        0.03022913],
       [0.        , 0.0059537 , 0.        , ..., 0.03393385, 0.03022913,
        1.        ]], shape=(4803, 4803))

In [10]:
similarity_matrix_lk[0]

array([1.        , 0.02058947, 0.01950882, ..., 0.02263226, 0.00418546,
       0.        ], shape=(4803,))

### Testing

In [11]:
movie_title = "John Carter"

In [12]:
try:
    print(df.loc[df["title"] == movie_title].index[0])
except IndexError:
    print("Movie not found")

4

In [13]:
idx1 = df.loc[df["title"] == movie_title].index[0]

In [14]:
similarity_scores1 = list(enumerate(similarity_matrix_lk[idx1]))
similarity_scores1

[(0, np.float64(0.21837177908295544)),
 (1, np.float64(0.0425564224101914)),
 (2, np.float64(0.027709502255834545)),
 (3, np.float64(0.009141308678371426)),
 (4, np.float64(1.0)),
 (5, np.float64(0.02555240391004328)),
 (6, np.float64(0.028167442431043698)),
 (7, np.float64(0.07628992159593384)),
 (8, np.float64(0.00484892351264347)),
 (9, np.float64(0.025731729415188823)),
 (10, np.float64(0.08994163456990156)),
 (11, np.float64(0.010808915399304451)),
 (12, np.float64(0.05895681466344285)),
 (13, np.float64(0.011686767573958527)),
 (14, np.float64(0.09023591253191414)),
 (15, np.float64(0.03144546434967247)),
 (16, np.float64(0.07593355214224291)),
 (17, np.float64(0.06455653655014135)),
 (18, np.float64(0.09219455232522032)),
 (19, np.float64(0.04538456868527101)),
 (20, np.float64(0.018741847580870073)),
 (21, np.float64(0.042288041860381896)),
 (22, np.float64(0.03224755250545923)),
 (23, np.float64(0.027498626050663007)),
 (24, np.float64(0.04587387786405625)),
 (25, np.float64(0.01615688056286803)),
 (26, np.float64(0.11238684796836326)),
 (27, np.float64(0.09145812061736984)),
 (28, np.float64(0.04626964132786984)),
 (29, np.float64(0.015850785891970358)),
 (30, np.float64(0.0062981743677631)),
 (31, np.float64(0.05303541015499262)),
 (32, np.float64(0.05185732076469684)),
 (33, np.float64(0.06990059356134448)),
 (34, np.float64(0.0)),
 (35, np.float64(0.025009621981748505)),
 (36, np.float64(0.0698873102526714)),
 (37, np.float64(0.01756751570564392)),
 (38, np.float64(0.015909949313697738)),
 (39, np.float64(0.03120300770097919)),
 (40, np.float64(0.048938966321683736)),
 (41, np.float64(0.0945022124157447)),
 (42, np.float64(0.03212105456832934)),
 (43, np.float64(0.027068940364576726)),
 (44, np.float64(0.032957446092670324)),
 (45, np.float64(0.05096945604132469)),
 (46, np.float64(0.10751314792126382)),
 (47, np.float64(0.10286770537840173)),
 (48, np.float64(0.07178653005532813)),
 (49, np.float64(0.04672379712733155)),
 (50, np.float64(0.08421639501052015)),
 (51, np.float64(0.040403679199695536)),
 (52, np.float64(0.11270700937966524)),
 (53, np.float64(0.06024091016965202)),
 (54, np.float64(0.030829926273127046)),
 (55, np.float64(0.023691616063056184)),
 (56, np.float64(0.06990005187855056)),
 (57, np.float64(0.012316805676511295)),
 (58, np.float64(0.03041918641800082)),
 (59, np.float64(0.05732202535127812)),
 (60, np.float64(0.015224369416262103)),
 (61, np.float64(0.06069655963612866)),
 (62, np.float64(0.02094815275971324)),
 (63, np.float64(0.02496556336243918)),
 (64, np.float64(0.05980229558316548)),
 (65, np.float64(0.013613226671022879)),
 (66, np.float64(0.011634162492539825)),
 (67, np.float64(0.06351530966756147)),
 (68, np.float64(0.026212426740091613)),
 (69, np.float64(0.01737353177126895)),
 (70, np.float64(0.06603314191273355)),
 (71, np.float64(0.026752787218233653)),
 (72, np.float64(0.015820173398333665)),
 (73, np.float64(0.0)),
 (74, np.float64(0.09180281044790697)),
 (75, np.float64(0.052675460267189514)),
 (76, np.float64(0.042916120969395656)),
 (77, np.float64(0.023128027459718453)),
 (78, np.float64(0.01945995153572625)),
 (79, np.float64(0.04085884963494448)),
 (80, np.float64(0.011848456065462531)),
 (81, np.float64(0.04270457298931251)),
 (82, np.float64(0.04427235436971512)),
 (83, np.float64(0.06134829480060916)),
 (84, np.float64(0.05935313407062079)),
 (85, np.float64(0.08153545875262491)),
 (86, np.float64(0.02056714226367699)),
 (87, np.float64(0.032427332483115634)),
 (88, np.float64(0.0193334158561767)),
 (89, np.float64(0.021839249596428696)),
 (90, np.float64(0.004070512765265309)),
 (91, np.float64(0.15011194623573346)),
 (92, np.float64(0.015962210328222697)),
 (93, np.float64(0.03316107893989704)),
 (94, np.float64(0.04450464218747181)),
 (95, np.float64(0.07187920733806005)),
 (96, np.float64(0.017952425452186952)),
 (97, np.float64(0.027716765247279465)),
 (98, np.float64(0.0180526701563799)),
 (99, np.float64(0.01292318852596924)),
 (100, np.float64(0.015955243698991192)),
 (101, np.float64(0.07180120331848001)),
 (102, np.float64(0.04863513742679259)),
 (103, np.float64(0.009651465309743342)),
 (104, np.float64(0.016331511031608924)),
 (105, np.float64(0.036097742528803975)),
 (106, np.float64(0.003171484081937573)),
 (107, np.float64(0.10782966622308243)),
 (108, np.float64(0.06941542186983593)),
 (109, np.float64(0.033797505314612605)),
 (110, np.float64(0.018352235190749563)),
 (111, np.float64(0.06656090878088872)),
 (112, np.float64(0.021434498219072763)),
 (113, np.float64(0.021747198474307068)),
 (114, np.float64(0.028193014374018596)),
 (115, np.float64(0.03322718187433711)),
 (116, np.float64(0.028649482311503157)),
 (117, np.float64(0.029257870429295955)),
 (118, np.float64(0.009968846154831014)),
 (119, np.float64(0.016882896691630282)),
 (120, np.float64(0.010604697529110111)),
 (121, np.float64(0.008966336512318679)),
 (122, np.float64(0.023555565609275516)),
 (123, np.float64(0.03304952034114728)),
 (124, np.float64(0.042730379232339376)),
 (125, np.float64(0.02675340359982597)),
 (126, np.float64(0.03348324403047048)),
 (127, np.float64(0.08365485144408476)),
 (128, np.float64(0.02520074808428042)),
 (129, np.float64(0.03298548376515823)),
 (130, np.float64(0.012925735623834969)),
 (131, np.float64(0.022090096695467874)),
 (132, np.float64(0.031065550071618573)),
 (133, np.float64(0.015307926111538181)),
 (134, np.float64(0.007988908314642424)),
 (135, np.float64(0.0)),
 (136, np.float64(0.003434307732812942)),
 (137, np.float64(0.02403397004773178)),
 (138, np.float64(0.020741421114579165)),
 (139, np.float64(0.013341931341757396)),
 (140, np.float64(0.01416244677912311)),
 (141, np.float64(0.17093228926885634)),
 (142, np.float64(0.00746407824131302)),
 (143, np.float64(0.015104060022083553)),
 (144, np.float64(0.023314580891877906)),
 (145, np.float64(0.027585267701346835)),
 (146, np.float64(0.03071683897229329)),
 (147, np.float64(0.024914129731516053)),
 (148, np.float64(0.003099516561507226)),
 (149, np.float64(0.04932999095904397)),
 (150, np.float64(0.07781856728950504)),
 (151, np.float64(0.02916674803734991)),
 (152, np.float64(0.028897262611497603)),
 (153, np.float64(0.005528513228293019)),
 (154, np.float64(0.0054660633903874135)),
 (155, np.float64(0.04806592012901285)),
 (156, np.float64(0.05400879834737264)),
 (157, np.float64(0.030427202324415283)),
 (158, np.float64(0.0705778006840272)),
 (159, np.float64(0.0033562135962635978)),
 (160, np.float64(0.06361966418469672)),
 (161, np.float64(0.006840223325014163)),
 (162, np.float64(0.03826888640353155)),
 (163, np.float64(0.03987113910552462)),
 (164, np.float64(0.013857694650015528)),
 (165, np.float64(0.057477186974452296)),
 (166, np.float64(0.01860685012094902)),
 (167, np.float64(0.008393476609970146)),
 (168, np.float64(0.08128076923035212)),
 (169, np.float64(0.081400715102608)),
 (170, np.float64(0.021524734220724286)),
 (171, np.float64(0.018028207770009803)),
 (172, np.float64(0.019763391332285593)),
 (173, np.float64(0.020601471380781756)),
 (174, np.float64(0.08688877351907356)),
 (175, np.float64(0.019630719120656465)),
 (176, np.float64(0.04245022358028839)),
 (177, np.float64(0.013538438024819717)),
 (178, np.float64(0.003379274348490476)),
 (179, np.float64(0.027665412687158157)),
 (180, np.float64(0.021052998237372462)),
 (181, np.float64(0.0027087681024565435)),
 (182, np.float64(0.057697059885780014)),
 (183, np.float64(0.048502010923356625)),
 (184, np.float64(0.12217237202975337)),
 (185, np.float64(0.04027130151555757)),
 (186, np.float64(0.006433815660150348)),
 (187, np.float64(0.02572608885616938)),
 (188, np.float64(0.021056527152755748)),
 (189, np.float64(0.028118131030504576)),
 (190, np.float64(0.0543967937342272)),
 (191, np.float64(0.012715521447160675)),
 (192, np.float64(0.03303798561366553)),
 (193, np.float64(0.038911309690075654)),
 (194, np.float64(0.003042323154777301)),
 (195, np.float64(0.0210211488499102)),
 (196, np.float64(0.01901518330256293)),
 (197, np.float64(0.025502037694556827)),
 (198, np.float64(0.02911227263180261)),
 (199, np.float64(0.026982611900374542)),
 (200, np.float64(0.09358786515739557)),
 (201, np.float64(0.01341584457997488)),
 (202, np.float64(0.004022677372840397)),
 (203, np.float64(0.04503743744231071)),
 (204, np.float64(0.024376993917527606)),
 (205, np.float64(0.04114431106962375)),
 (206, np.float64(0.02187648106456931)),
 (207, np.float64(0.15950633003233078)),
 (208, np.float64(0.013133876652587969)),
 (209, np.float64(0.005300404841633203)),
 (210, np.float64(0.0026522160045000034)),
 (211, np.float64(0.015554915449625482)),
 (212, np.float64(0.01919307675703899)),
 (213, np.float64(0.028111645544864002)),
 (214, np.float64(0.016466117821758212)),
 (215, np.float64(0.06312500725887712)),
 (216, np.float64(0.006545579891964009)),
 (217, np.float64(0.038190644851799106)),
 (218, np.float64(0.025102287819874888)),
 (219, np.float64(0.009044292242532464)),
 (220, np.float64(0.04762958600855763)),
 (221, np.float64(0.009039350125291182)),
 (222, np.float64(0.0649706622929183)),
 (223, np.float64(0.07962356085870406)),
 (224, np.float64(0.020666069161743985)),
 (225, np.float64(0.04457590190097348)),
 (226, np.float64(0.0)),
 (227, np.float64(0.03194241773218555)),
 (228, np.float64(0.07622042150910657)),
 (229, np.float64(0.028833478873028104)),
 (230, np.float64(0.08297828793577455)),
 (231, np.float64(0.004477802255400598)),
 (232, np.float64(0.07462330420992203)),
 (233, np.float64(0.0348624682189599)),
 (234, np.float64(0.017347944099794368)),
 (235, np.float64(0.016262551443784492)),
 (236, np.float64(0.031711178785930674)),
 (237, np.float64(0.0075317929953977805)),
 (238, np.float64(0.03508204103812809)),
 (239, np.float64(0.04298034673537457)),
 (240, np.float64(0.004719182027675281)),
 (241, np.float64(0.03058411397625087)),
 (242, np.float64(0.03668589752477381)),
 (243, np.float64(0.02947308166373451)),
 (244, np.float64(0.01610493485469308)),
 (245, np.float64(0.009779307745131232)),
 (246, np.float64(0.043539036401099414)),
 (247, np.float64(0.017621240028839077)),
 (248, np.float64(0.013592734879135416)),
 (249, np.float64(0.06229257753614253)),
 (250, np.float64(0.0)),
 (251, np.float64(0.054804080072256595)),
 (252, np.float64(0.002199130936260189)),
 (253, np.float64(0.07637091042119364)),
 (254, np.float64(0.025535601999185604)),
 (255, np.float64(0.0093118413067431)),
 (256, np.float64(0.0737743179571958)),
 (257, np.float64(0.03184028088628701)),
 (258, np.float64(0.015247317444325333)),
 (259, np.float64(0.0075998390445735)),
 (260, np.float64(0.1501257762643834)),
 (261, np.float64(0.02439021955179113)),
 (262, np.float64(0.059464398023623924)),
 (263, np.float64(0.01872111502222268)),
 (264, np.float64(0.0)),
 (265, np.float64(0.02552491247254638)),
 (266, np.float64(0.05637902443809757)),
 (267, np.float64(0.03481462419443784)),
 (268, np.float64(0.03313071401990618)),
 (269, np.float64(0.04722450699285721)),
 (270, np.float64(0.22336228036126748)),
 (271, np.float64(0.054451197075205654)),
 (272, np.float64(0.0)),
 (273, np.float64(0.015118850819628537)),
 (274, np.float64(0.030580051002566836)),
 (275, np.float64(0.048274939909876066)),
 (276, np.float64(0.01574022145142378)),
 (277, np.float64(0.00870766785708638)),
 (278, np.float64(0.1363541009502649)),
 (279, np.float64(0.028059302400169104)),
 (280, np.float64(0.042698720820770135)),
 (281, np.float64(0.018628634336220525)),
 (282, np.float64(0.002612736874744314)),
 (283, np.float64(0.0)),
 (284, np.float64(0.007155305715546955)),
 (285, np.float64(0.0022782516030241764)),
 (286, np.float64(0.018246338653058015)),
 (287, np.float64(0.04689006995220468)),
 (288, np.float64(0.06091415177005149)),
 (289, np.float64(0.011441370984633562)),
 (290, np.float64(0.007544609083038982)),
 (291, np.float64(0.020965988380656192)),
 (292, np.float64(0.05725800117011019)),
 (293, np.float64(0.0)),
 (294, np.float64(0.06437341183069578)),
 (295, np.float64(0.013368274381585412)),
 (296, np.float64(0.005677228038754639)),
 (297, np.float64(0.006293117797707691)),
 (298, np.float64(0.01771294027167624)),
 (299, np.float64(0.013784482369402214)),
 (300, np.float64(0.06681032233029288)),
 (301, np.float64(0.06765005504600952)),
 (302, np.float64(0.017999820946906213)),
 (303, np.float64(0.0026389201769344626)),
 (304, np.float64(0.02940064085889859)),
 (305, np.float64(0.11823832839578742)),
 (306, np.float64(0.05325361776354819)),
 (307, np.float64(0.025760638854659054)),
 (308, np.float64(0.01822448951341417)),
 (309, np.float64(0.004811436890149025)),
 (310, np.float64(0.04533226180823317)),
 (311, np.float64(0.02269669249711123)),
 (312, np.float64(0.010383907628190983)),
 (313, np.float64(0.043069265234973196)),
 (314, np.float64(0.0)),
 (315, np.float64(0.006836606944507776)),
 (316, np.float64(0.005273140011229636)),
 (317, np.float64(0.008849530438052837)),
 (318, np.float64(0.0070966102731647935)),
 (319, np.float64(0.02165322214110127)),
 (320, np.float64(0.01422698223676172)),
 (321, np.float64(0.0)),
 (322, np.float64(0.11106991728629736)),
 (323, np.float64(0.03007519649808817)),
 (324, np.float64(0.025928876198495363)),
 (325, np.float64(0.012106582255144714)),
 (326, np.float64(0.0)),
 (327, np.float64(0.019222516449774102)),
 (328, np.float64(0.0)),
 (329, np.float64(0.05309192869334667)),
 (330, np.float64(0.042073757280360974)),
 (331, np.float64(0.05300113900514347)),
 (332, np.float64(0.02572549193607252)),
 (333, np.float64(0.01090596410054031)),
 (334, np.float64(0.04195102690076382)),
 (335, np.float64(0.011430491300993037)),
 (336, np.float64(0.008619960224015477)),
 (337, np.float64(0.028490631572928044)),
 (338, np.float64(0.011460827373023754)),
 (339, np.float64(0.018954643779038702)),
 (340, np.float64(0.022377971127131364)),
 (341, np.float64(0.031349423203841514)),
 (342, np.float64(0.06453969592496653)),
 (343, np.float64(0.0)),
 (344, np.float64(0.01858090656576262)),
 (345, np.float64(0.023073762367736266)),
 (346, np.float64(0.0)),
 (347, np.float64(0.0053719932772978655)),
 (348, np.float64(0.016945291228709605)),
 (349, np.float64(0.007913423198389176)),
 (350, np.float64(0.006384010977275846)),
 (351, np.float64(0.0)),
 (352, np.float64(0.03660680312746119)),
 (353, np.float64(0.006927018264442166)),
 (354, np.float64(0.03947295347303264)),
 (355, np.float64(0.016112248394371798)),
 (356, np.float64(0.04637089790422065)),
 (357, np.float64(0.0)),
 (358, np.float64(0.021204470834673965)),
 (359, np.float64(0.005156600133759628)),
 (360, np.float64(0.03683150206907807)),
 (361, np.float64(0.01711087742559198)),
 (362, np.float64(0.09180900145459583)),
 (363, np.float64(0.04076266673964304)),
 (364, np.float64(0.0)),
 (365, np.float64(0.07975338250152045)),
 (366, np.float64(0.019942548728922965)),
 (367, np.float64(0.023148091976000377)),
 (368, np.float64(0.034018912139864604)),
 (369, np.float64(0.039340304839893654)),
 (370, np.float64(0.01310002840144782)),
 (371, np.float64(0.017733663629061723)),
 (372, np.float64(0.009517814828753902)),
 (373, np.float64(0.2924522182020951)),
 (374, np.float64(0.015595611818405408)),
 (375, np.float64(0.01038449761120035)),
 (376, np.float64(0.01112945560106307)),
 (377, np.float64(0.0)),
 (378, np.float64(0.013214938361290604)),
 (379, np.float64(0.04532237835270351)),
 (380, np.float64(0.004559929344871264)),
 (381, np.float64(0.0054089638242935745)),
 (382, np.float64(0.013901397278248996)),
 (383, np.float64(0.004832007111720961)),
 (384, np.float64(0.03242442785098426)),
 (385, np.float64(0.004764795851414046)),
 (386, np.float64(0.05075709238119976)),
 (387, np.float64(0.02356532741269278)),
 (388, np.float64(0.01711599135923094)),
 (389, np.float64(0.056294410086783674)),
 (390, np.float64(0.004816786455250614)),
 (391, np.float64(0.03145530320291473)),
 (392, np.float64(0.014293583843454489)),
 (393, np.float64(0.0)),
 (394, np.float64(0.002415741756705283)),
 (395, np.float64(0.015206468461553721)),
 (396, np.float64(0.00923982155282889)),
 (397, np.float64(0.0)),
 (398, np.float64(0.0)),
 (399, np.float64(0.0033289728861724114)),
 (400, np.float64(0.07758889339272357)),
 (401, np.float64(0.03586955125737954)),
 (402, np.float64(0.022103575044005144)),
 (403, np.float64(0.018746521581987717)),
 (404, np.float64(0.04091428365551541)),
 (405, np.float64(0.02853764401389163)),
 (406, np.float64(0.0040607520645429855)),
 (407, np.float64(0.01547549297786056)),
 (408, np.float64(0.00897955189871469)),
 (409, np.float64(0.003198892543879886)),
 (410, np.float64(0.034044660003694716)),
 (411, np.float64(0.012834378502601662)),
 (412, np.float64(0.050644144966172776)),
 (413, np.float64(0.012604451748632246)),
 (414, np.float64(0.004589839375951489)),
 (415, np.float64(0.035847679765508386)),
 (416, np.float64(0.017453596410983492)),
 (417, np.float64(0.013155050717937811)),
 (418, np.float64(0.028056559397396423)),
 (419, np.float64(0.07550640771544326)),
 (420, np.float64(0.05500422525302216)),
 (421, np.float64(0.007249698875701743)),
 (422, np.float64(0.021803618858573102)),
 (423, np.float64(0.0)),
 (424, np.float64(0.03411473671263209)),
 (425, np.float64(0.01444838643085038)),
 (426, np.float64(0.05524577772970127)),
 (427, np.float64(0.004101754971136628)),
 (428, np.float64(0.008911134461398658)),
 (429, np.float64(0.007069183370275419)),
 (430, np.float64(0.05731803504207998)),
 (431, np.float64(0.012091770709253814)),
 (432, np.float64(0.056902846667852454)),
 (433, np.float64(0.0038856647910543783)),
 (434, np.float64(0.010424234459624086)),
 (435, np.float64(0.0)),
 (436, np.float64(0.0)),
 (437, np.float64(0.013291412860942351)),
 (438, np.float64(0.0)),
 (439, np.float64(0.04310140673070135)),
 (440, np.float64(0.0045131915040051065)),
 (441, np.float64(0.01864072823528562)),
 (442, np.float64(0.03715576587756088)),
 (443, np.float64(0.03258067881324828)),
 (444, np.float64(0.03175916750823156)),
 (445, np.float64(0.008212934411152832)),
 (446, np.float64(0.016219767738211526)),
 (447, np.float64(0.014638586467406779)),
 (448, np.float64(0.023242488185534833)),
 (449, np.float64(0.01869859538854994)),
 (450, np.float64(0.009569337425914195)),
 (451, np.float64(0.014495457016960787)),
 (452, np.float64(0.0)),
 (453, np.float64(0.0026019551674345133)),
 (454, np.float64(0.10585349106843946)),
 (455, np.float64(0.010957908139867025)),
 (456, np.float64(0.028415258127321423)),
 (457, np.float64(0.019830318217845623)),
 (458, np.float64(0.013706145593586974)),
 (459, np.float64(0.02398265723199869)),
 (460, np.float64(0.0)),
 (461, np.float64(0.0811925941059343)),
 (462, np.float64(0.03555856793542404)),
 (463, np.float64(0.0)),
 (464, np.float64(0.0)),
 (465, np.float64(0.0)),
 (466, np.float64(0.09736509052387672)),
 (467, np.float64(0.012748624625245602)),
 (468, np.float64(0.0025523343233903543)),
 (469, np.float64(0.025387134960132885)),
 (470, np.float64(0.0)),
 (471, np.float64(0.013276272884213786)),
 (472, np.float64(0.018511653619330562)),
 (473, np.float64(0.21704442625661668)),
 (474, np.float64(0.0)),
 (475, np.float64(0.03593419967142952)),
 (476, np.float64(0.025778632139678636)),
 (477, np.float64(0.022928007959503078)),
 (478, np.float64(0.04965828054561082)),
 (479, np.float64(0.03623415529516998)),
 (480, np.float64(0.0968937546289195)),
 (481, np.float64(0.009092777643602386)),
 (482, np.float64(0.0)),
 (483, np.float64(0.052760333577600196)),
 (484, np.float64(0.004420336987764383)),
 (485, np.float64(0.0038025478082094285)),
 (486, np.float64(0.024324391783243405)),
 (487, np.float64(0.24232909219506604)),
 (488, np.float64(0.006680210569667095)),
 (489, np.float64(0.006526509801002232)),
 (490, np.float64(0.053852087537568594)),
 (491, np.float64(0.039357727280223215)),
 (492, np.float64(0.022213824675054512)),
 (493, np.float64(0.022889984222927297)),
 (494, np.float64(0.0)),
 (495, np.float64(0.059941300935813346)),
 (496, np.float64(0.004095471638100274)),
 (497, np.float64(0.012728557729549221)),

In [15]:
similarity_scores1 = sorted(similarity_scores1, key=lambda x: x[1], reverse=True)
similarity_scores1

[(4, np.float64(1.0)),
 (373, np.float64(0.2924522182020951)),
 (487, np.float64(0.24232909219506604)),
 (270, np.float64(0.22336228036126748)),
 (0, np.float64(0.21837177908295544)),
 (473, np.float64(0.21704442625661668)),
 (778, np.float64(0.19004216074766256)),
 (141, np.float64(0.17093228926885634)),
 (1201, np.float64(0.16082432779344413)),
 (207, np.float64(0.15950633003233078)),
 (754, np.float64(0.15892089750534483)),
 (3668, np.float64(0.1554443447112357)),
 (2964, np.float64(0.15534516124253708)),
 (1198, np.float64(0.15217474796304847)),
 (260, np.float64(0.1501257762643834)),
 (91, np.float64(0.15011194623573346)),
 (1068, np.float64(0.1486110516457408)),
 (278, np.float64(0.1363541009502649)),
 (1768, np.float64(0.1350733451236379)),
 (581, np.float64(0.1342128206352034)),
 (1319, np.float64(0.13349691161539223)),
 (1326, np.float64(0.13217905145740938)),
 (3904, np.float64(0.1269635528599881)),
 (539, np.float64(0.12676866096017353)),
 (1415, np.float64(0.1257924950018353)),
 (692, np.float64(0.1239610164833793)),
 (502, np.float64(0.12393652875672428)),
 (838, np.float64(0.12372040721632127)),
 (184, np.float64(0.12217237202975337)),
 (2403, np.float64(0.12210709490501458)),
 (972, np.float64(0.12037645932167926)),
 (305, np.float64(0.11823832839578742)),
 (595, np.float64(0.11728019271545115)),
 (1709, np.float64(0.11624063037795428)),
 (1144, np.float64(0.11326800612965954)),
 (52, np.float64(0.11270700937966524)),
 (26, np.float64(0.11238684796836326)),
 (1341, np.float64(0.11200241234410908)),
 (322, np.float64(0.11106991728629736)),
 (2696, np.float64(0.11079830308360152)),
 (1735, np.float64(0.10989729263061072)),
 (541, np.float64(0.10899877152564487)),
 (1959, np.float64(0.10814796080034877)),
 (107, np.float64(0.10782966622308243)),
 (46, np.float64(0.10751314792126382)),
 (454, np.float64(0.10585349106843946)),
 (1482, np.float64(0.1057830522093294)),
 (833, np.float64(0.10528318288610725)),
 (3155, np.float64(0.10516354921204181)),
 (752, np.float64(0.10440073809481207)),
 (870, np.float64(0.10408624718618832)),
 (3494, np.float64(0.10393474468177463)),
 (47, np.float64(0.10286770537840173)),
 (2433, np.float64(0.10166160881447321)),
 (3993, np.float64(0.10120216675489105)),
 (1318, np.float64(0.10106930632114314)),
 (939, np.float64(0.10097018219630055)),
 (4042, np.float64(0.09933851143332732)),
 (3158, np.float64(0.09796989499256344)),
 (4401, np.float64(0.09787943769648029)),
 (466, np.float64(0.09736509052387672)),
 (480, np.float64(0.0968937546289195)),
 (2755, np.float64(0.09680467391199843)),
 (41, np.float64(0.0945022124157447)),
 (2900, np.float64(0.09449354571554863)),
 (582, np.float64(0.09435340271726142)),
 (1015, np.float64(0.09431768387166797)),
 (200, np.float64(0.09358786515739557)),
 (1079, np.float64(0.09334394811061751)),
 (577, np.float64(0.09312101271493518)),
 (4332, np.float64(0.09265973427476433)),
 (18, np.float64(0.09219455232522032)),
 (813, np.float64(0.091894839853288)),
 (362, np.float64(0.09180900145459583)),
 (74, np.float64(0.09180281044790697)),
 (3068, np.float64(0.09173860552393583)),
 (2541, np.float64(0.0915695708085083)),
 (27, np.float64(0.09145812061736984)),
 (2015, np.float64(0.09104790133835189)),
 (3214, np.float64(0.09078620852179055)),
 (1976, np.float64(0.09062028016619658)),
 (14, np.float64(0.09023591253191414)),
 (10, np.float64(0.08994163456990156)),
 (507, np.float64(0.08955878297746131)),
 (1914, np.float64(0.08828350677357354)),
 (931, np.float64(0.08768492921468855)),
 (1564, np.float64(0.0869221206027566)),
 (174, np.float64(0.08688877351907356)),
 (1272, np.float64(0.08600007605367084)),
 (2966, np.float64(0.08519004986926086)),
 (1217, np.float64(0.08476856428888802)),
 (50, np.float64(0.08421639501052015)),
 (4176, np.float64(0.08395911678493709)),
 (127, np.float64(0.08365485144408476)),
 (564, np.float64(0.08356304499797015)),
 (230, np.float64(0.08297828793577455)),
 (694, np.float64(0.08238966215826715)),
 (1086, np.float64(0.08198131356489667)),
 (1016, np.float64(0.0819485588078812)),
 (85, np.float64(0.08153545875262491)),
 (169, np.float64(0.081400715102608)),
 (2781, np.float64(0.08133710833522971)),
 (168, np.float64(0.08128076923035212)),
 (461, np.float64(0.0811925941059343)),
 (1611, np.float64(0.08083488936576173)),
 (3195, np.float64(0.08083336108714154)),
 (1467, np.float64(0.08055614029580244)),
 (2258, np.float64(0.07990788274570802)),
 (365, np.float64(0.07975338250152045)),
 (223, np.float64(0.07962356085870406)),
 (1303, np.float64(0.07942948587899948)),
 (843, np.float64(0.07933673658328579)),
 (2444, np.float64(0.07890619556650176)),
 (150, np.float64(0.07781856728950504)),
 (400, np.float64(0.07758889339272357)),
 (1277, np.float64(0.0771427540155658)),
 (3750, np.float64(0.07685528575889607)),
 (4187, np.float64(0.07661757341624453)),
 (1213, np.float64(0.07651279238221623)),
 (253, np.float64(0.07637091042119364)),
 (7, np.float64(0.07628992159593384)),
 (1294, np.float64(0.07628175015142034)),
 (228, np.float64(0.07622042150910657)),
 (2934, np.float64(0.07597475705825046)),
 (16, np.float64(0.07593355214224291)),
 (3730, np.float64(0.07554531921621058)),
 (419, np.float64(0.07550640771544326)),
 (232, np.float64(0.07462330420992203)),
 (999, np.float64(0.07461134722154808)),
 (2912, np.float64(0.07419566498552092)),
 (1695, np.float64(0.07412357499720626)),
 (256, np.float64(0.0737743179571958)),
 (3405, np.float64(0.0730260285004757)),
 (3184, np.float64(0.07289419196185724)),
 (2327, np.float64(0.07253340900446867)),
 (773, np.float64(0.07217745610810629)),
 (1864, np.float64(0.07196345064752177)),
 (95, np.float64(0.07187920733806005)),
 (101, np.float64(0.07180120331848001)),
 (48, np.float64(0.07178653005532813)),
 (2100, np.float64(0.07157450198469603)),
 (1053, np.float64(0.07143638133559874)),
 (657, np.float64(0.07102100459072237)),
 (1974, np.float64(0.07096159767896268)),
 (158, np.float64(0.0705778006840272)),
 (1402, np.float64(0.0704185536161044)),
 (4542, np.float64(0.07015932312000647)),
 (1985, np.float64(0.07007399879373592)),
 (2278, np.float64(0.07003812267950213)),
 (33, np.float64(0.06990059356134448)),
 (56, np.float64(0.06990005187855056)),
 (36, np.float64(0.0698873102526714)),
 (1825, np.float64(0.06951995958723843)),
 (755, np.float64(0.06947899209513188)),
 (108, np.float64(0.06941542186983593)),
 (3386, np.float64(0.06896107094297982)),
 (1531, np.float64(0.06893269335078085)),
 (2936, np.float64(0.06785270469562471)),
 (3570, np.float64(0.0677918301270264)),
 (301, np.float64(0.06765005504600952)),
 (4651, np.float64(0.06754850397297825)),
 (529, np.float64(0.06682020421192321)),
 (300, np.float64(0.06681032233029288)),
 (111, np.float64(0.06656090878088872)),
 (1826, np.float64(0.06644873192130654)),
 (1377, np.float64(0.06606202260482888)),
 (70, np.float64(0.06603314191273355)),
 (2155, np.float64(0.06602030569675993)),
 (2509, np.float64(0.06545662674484606)),
 (740, np.float64(0.0653722229324322)),
 (1465, np.float64(0.06503640375370665)),
 (222, np.float64(0.0649706622929183)),
 (1438, np.float64(0.06470498519735737)),
 (17, np.float64(0.06455653655014135)),
 (342, np.float64(0.06453969592496653)),
 (1715, np.float64(0.06445667262731902)),
 (294, np.float64(0.06437341183069578)),
 (2317, np.float64(0.06435875960646309)),
 (1951, np.float64(0.06434886059907792)),
 (661, np.float64(0.0637062522302694)),
 (2390, np.float64(0.0636552479251035)),
 (160, np.float64(0.06361966418469672)),
 (2410, np.float64(0.06353382210699168)),
 (67, np.float64(0.06351530966756147)),
 (2921, np.float64(0.06342807525203897)),
 (3072, np.float64(0.06342330133089924)),
 (1358, np.float64(0.06341956688857907)),
 (1175, np.float64(0.06339788543697199)),
 (2343, np.float64(0.06333610578663876)),
 (2482, np.float64(0.06317577693760171)),
 (1554, np.float64(0.06313857565460557)),
 (215, np.float64(0.06312500725887712)),
 (3568, np.float64(0.0630576175905733)),
 (3749, np.float64(0.0629863145399981)),
 (1995, np.float64(0.06297080997547087)),
 (854, np.float64(0.06272495054168171)),
 (889, np.float64(0.06258401064010168)),
 (628, np.float64(0.06251762644655035)),
 (3764, np.float64(0.062467436332247134)),
 (511, np.float64(0.06238335036780089)),
 (249, np.float64(0.06229257753614253)),
 (1286, np.float64(0.06221440136088845)),
 (3427, np.float64(0.06186641777702051)),
 (2909, np.float64(0.06168909580682094)),
 (4162, np.float64(0.06167050432039596)),
 (4131, np.float64(0.06161675374255497)),
 (83, np.float64(0.06134829480060916)),
 (1296, np.float64(0.061073301745300616)),
 (288, np.float64(0.06091415177005149)),
 (1254, np.float64(0.06091390088885944)),
 (61, np.float64(0.06069655963612866)),
 (1617, np.float64(0.060690948202279146)),
 (3534, np.float64(0.06041521550168167)),
 (53, np.float64(0.06024091016965202)),
 (2614, np.float64(0.06010690292542854)),
 (3133, np.float64(0.060017067987724375)),
 (1199, np.float64(0.05997017930677137)),
 (495, np.float64(0.059941300935813346)),
 (64, np.float64(0.05980229558316548)),
 (1643, np.float64(0.0596403727627064)),
 (4688, np.float64(0.05951811312153388)),
 (262, np.float64(0.059464398023623924)),
 (1917, np.float64(0.059376936788598976)),
 (84, np.float64(0.05935313407062079)),
 (1142, np.float64(0.05902172560777079)),
 (3129, np.float64(0.0590201958664046)),
 (12, np.float64(0.05895681466344285)),
 (4125, np.float64(0.058889390419843035)),
 (1412, np.float64(0.05877136093668852)),
 (671, np.float64(0.0587106424523004)),
 (2237, np.float64(0.05859396670667845)),
 (4117, np.float64(0.058297295936195176)),
 (609, np.float64(0.05823773453508565)),
 (624, np.float64(0.05815290446168808)),
 (1274, np.float64(0.05810029727490299)),
 (1518, np.float64(0.05802397468541391)),
 (1007, np.float64(0.05772804341355858)),
 (2492, np.float64(0.05770874671122539)),
 (182, np.float64(0.057697059885780014)),
 (1891, np.float64(0.05757526306242604)),
 (1759, np.float64(0.05749407149603364)),
 (165, np.float64(0.057477186974452296)),
 (59, np.float64(0.05732202535127812)),
 (430, np.float64(0.05731803504207998)),
 (292, np.float64(0.05725800117011019)),
 (4225, np.float64(0.05708465261566079)),
 (432, np.float64(0.056902846667852454)),
 (3373, np.float64(0.056597113539139626)),
 (2341, np.float64(0.05646272470001376)),
 (1163, np.float64(0.056457988619947164)),
 (1027, np.float64(0.05641983728386116)),
 (266, np.float64(0.05637902443809757)),
 (1468, np.float64(0.05631014114475633)),
 (389, np.float64(0.056294410086783674)),
 (768, np.float64(0.05627450208696469)),
 (1478, np.float64(0.05615435030352729)),
 (2724, np.float64(0.055849031028371854)),
 (977, np.float64(0.05573402510565023)),
 (426, np.float64(0.05524577772970127)),
 (1177, np.float64(0.05506884266951176)),
 (420, np.float64(0.05500422525302216)),
 (632, np.float64(0.0549144445002536)),
 (2192, np.float64(0.05483477019169525)),
 (251, np.float64(0.054804080072256595)),
 (2860, np.float64(0.05476601674977205)),
 (2198, np.float64(0.054610512190711176)),
 (2726, np.float64(0.05449809867398558)),
 (505, np.float64(0.05449664638871706)),
 (3899, np.float64(0.0544816283230123)),
 (271, np.float64(0.054451197075205654)),
 (190, np.float64(0.0543967937342272)),
 (1399, np.float64(0.05439305784103755)),
 (1129, np.float64(0.054129250743558704)),
 (2285, np.float64(0.05412890668713653)),
 (1524, np.float64(0.0540353900388803)),
 (156, np.float64(0.05400879834737264)),
 (2011, np.float64(0.053948215274415)),
 (490, np.float64(0.053852087537568594)),
 (4108, np.float64(0.05377363914772308)),
 (1224, np.float64(0.05374705430738361)),
 (1990, np.float64(0.05342096191119345)),
 (986, np.float64(0.0532601991863344)),
 (306, np.float64(0.05325361776354819)),
 (549, np.float64(0.05321698032269666)),
 (1028, np.float64(0.05315020813971961)),
 (941, np.float64(0.053138116043127)),
 (329, np.float64(0.05309192869334667)),
 (812, np.float64(0.05308357877014468)),
 (31, np.float64(0.05303541015499262)),
 (331, np.float64(0.05300113900514347)),
 (1633, np.float64(0.052980466924626685)),
 (2561, np.float64(0.05293595221652502)),
 (483, np.float64(0.052760333577600196)),
 (75, np.float64(0.052675460267189514)),
 (787, np.float64(0.05260064547865255)),
 (3396, np.float64(0.05224319217743821)),
 (1300, np.float64(0.051938378971392585)),
 (32, np.float64(0.05185732076469684)),
 (4653, np.float64(0.05170729798931403)),
 (3191, np.float64(0.05163192227742426)),
 (643, np.float64(0.05159989791001904)),
 (1606, np.float64(0.051573188003140716)),
 (2630, np.float64(0.051506425168093235)),
 (1999, np.float64(0.05147395769780882)),
 (2735, np.float64(0.051452993304609236)),
 (1650, np.float64(0.05128454267636002)),
 (1030, np.float64(0.051124175956042336)),
 (45, np.float64(0.05096945604132469)),
 (2229, np.float64(0.05093311580885938)),
 (386, np.float64(0.05075709238119976)),
 (412, np.float64(0.050644144966172776)),
 (2826, np.float64(0.050452524303986605)),
 (4535, np.float64(0.050339762209627825)),
 (1158, np.float64(0.05008343418723745)),
 (478, np.float64(0.04965828054561082)),
 (498, np.float64(0.04957449381896848)),
 (2069, np.float64(0.04955130566656045)),
 (1877, np.float64(0.049420247485351565)),
 (1451, np.float64(0.04938798390638905)),
 (4470, np.float64(0.04933442165253503)),
 (149, np.float64(0.04932999095904397)),
 (4385, np.float64(0.04922756242995996)),
 (3971, np.float64(0.0489627943341852)),
 (40, np.float64(0.048938966321683736)),
 (1649, np.float64(0.048788980122564704)),
 (678, np.float64(0.048679903915192606)),
 (920, np.float64(0.04865529437479186)),
 (102, np.float64(0.04863513742679259)),
 (1508, np.float64(0.04858459084670119)),
 (2134, np.float64(0.04850644595888962)),
 (183, np.float64(0.048502010923356625)),
 (1395, np.float64(0.048443777393476446)),
 (1822, np.float64(0.048415217882374996)),
 (4274, np.float64(0.048369583556962206)),
 (275, np.float64(0.048274939909876066)),
 (1044, np.float64(0.04820583881678036)),
 (3914, np.float64(0.048168079460790894)),
 (1111, np.float64(0.04811579259014097)),
 (2967, np.float64(0.04807384772711907)),
 (155, np.float64(0.04806592012901285)),
 (4661, np.float64(0.047786919211060666)),
 (220, np.float64(0.04762958600855763)),
 (1092, np.float64(0.04759961787044208)),
 (1001, np.float64(0.0475449868290108)),
 (3948, np.float64(0.04744173011860292)),
 (269, np.float64(0.04722450699285721)),
 (2550, np.float64(0.047179551246742536)),
 (1902, np.float64(0.0471261008674486)),
 (1800, np.float64(0.04710191904004755)),
 (599, np.float64(0.04705624671396902)),
 (500, np.float64(0.04703779662333693)),
 (287, np.float64(0.04689006995220468)),
 (2296, np.float64(0.04686710582897506)),
 (791, np.float64(0.04682199489072984)),
 (2757, np.float64(0.04678172698871934)),
 (2380, np.float64(0.046764236566362985)),
 (1551, np.float64(0.04675219018043318)),
 (49, np.float64(0.04672379712733155)),
 (1268, np.float64(0.046670611242165067)),
 (3024, np.float64(0.04662691779519909)),
 (2016, np.float64(0.04662155413296275)),
 (3776, np.float64(0.046604750240590284)),
 (356, np.float64(0.04637089790422065)),
 (28, np.float64(0.04626964132786984)),
 (658, np.float64(0.046225780148429714)),
 (2044, np.float64(0.0461432188206152)),
 (2265, np.float64(0.04599324895706343)),
 (2224, np.float64(0.04591522822966477)),
 (2300, np.float64(0.045913050857143506)),
 (24, np.float64(0.04587387786405625)),
 (4623, np.float64(0.045865955644773235)),
 (1057, np.float64(0.04574681402199713)),
 (680, np.float64(0.04564728264170282)),
 (626, np.float64(0.045585837939883564)),
 (1034, np.float64(0.04546291176250745)),
 (4161, np.float64(0.04541533939636119)),
 (19, np.float64(0.04538456868527101)),
 (310, np.float64(0.04533226180823317)),
 (379, np.float64(0.04532237835270351)),
 (610, np.float64(0.04526913927704564)),
 (1698, np.float64(0.04522872201328447)),
 (1103, np.float64(0.0452167792885871)),
 (800, np.float64(0.045096421319870114)),
 (203, np.float64(0.04503743744231071)),
 (2587, np.float64(0.04486926452548613)),
 (647, np.float64(0.044844018503068725)),
 (637, np.float64(0.0448365308584409)),
 (3698, np.float64(0.0447662544125166)),
 (1029, np.float64(0.04467418860711343)),
 (4621, np.float64(0.04465215281335504)),
 (225, np.float64(0.04457590190097348)),
 (1019, np.float64(0.04455443951701761)),
 (3353, np.float64(0.0445056954053403)),
 (94, np.float64(0.04450464218747181)),
 (82, np.float64(0.04427235436971512)),
 (1352, np.float64(0.044149960620937886)),
 (621, np.float64(0.044103680510433604)),
 (3604, np.float64(0.04408788854088939)),
 (1905, np.float64(0.04408770817061204)),
 (2727, np.float64(0.04401382168987876)),
 (4339, np.float64(0.0440073564975623)),
 (3215, np.float64(0.04395619869711831)),
 (587, np.float64(0.04393902945694317)),
 (3325, np.float64(0.04393515568717497)),
 (3229, np.float64(0.04386405061420279)),
 (642, np.float64(0.04379108567359397)),
 (1672, np.float64(0.04369621531562408)),
 (2449, np.float64(0.04367524139984179)),
 (246, np.float64(0.043539036401099414)),
 (770, np.float64(0.043531366983724375)),
 (1186, np.float64(0.043477523082999875)),
 (2862, np.float64(0.0433595744335287)),
 (2416, np.float64(0.0433364961130003)),
 (3991, np.float64(0.043307760859809794)),
 (1490, np.float64(0.0432798672236967)),
 (2029, np.float64(0.043277635919631324)),
 (669, np.float64(0.043240443495275914)),
 (3498, np.float64(0.04320144682706144)),
 (2944, np.float64(0.0432007735474554)),
 (510, np.float64(0.04314194833415985)),
 (4201, np.float64(0.043131133581473996)),
 (439, np.float64(0.04310140673070135)),
 (313, np.float64(0.043069265234973196)),
 (4556, np.float64(0.043017407811460344)),
 (2925, np.float64(0.0429809842463376)),
 (239, np.float64(0.04298034673537457)),
 (1042, np.float64(0.04293764886974012)),
 (76, np.float64(0.042916120969395656)),
 (2522, np.float64(0.042836441558394146)),
 (124, np.float64(0.042730379232339376)),
 (633, np.float64(0.04271458066120782)),
 (81, np.float64(0.04270457298931251)),
 (280, np.float64(0.042698720820770135)),
 (3378, np.float64(0.04256309616896853)),
 (1, np.float64(0.0425564224101914)),
 (176, np.float64(0.04245022358028839)),
 (1083, np.float64(0.042413075551332204)),
 (21, np.float64(0.042288041860381896)),
 (2772, np.float64(0.042209832592795975)),
 (3722, np.float64(0.0421905794534724)),
 (1473, np.float64(0.04215837567408523)),
 (629, np.float64(0.04209291008097585)),
 (2658, np.float64(0.04208014102258764)),
 (330, np.float64(0.042073757280360974)),
 (2716, np.float64(0.04205141940121278)),
 (3018, np.float64(0.042048829122669155)),
 (1442, np.float64(0.04202765713850029)),
 (799, np.float64(0.0419828179419616)),
 (4062, np.float64(0.04195833904235985)),
 (1433, np.float64(0.04195234744247292)),
 (334, np.float64(0.04195102690076382)),
 (1285, np.float64(0.04191144385388112)),
 (2247, np.float64(0.04187644956311345)),
 (2760, np.float64(0.04179510234013476)),
 (2235, np.float64(0.04164595932738856)),
 (1510, np.float64(0.04164206395532398)),
 (2442, np.float64(0.04160666565711419)),
 (973, np.float64(0.04155153837312596)),
 (2047, np.float64(0.04153407082587787)),
 (3143, np.float64(0.04150344240588642)),
 (4700, np.float64(0.04145931041785758)),
 (2505, np.float64(0.041276856883678645)),
 (908, np.float64(0.04127379966455874)),
 (4009, np.float64(0.041246482380785286)),
 (3556, np.float64(0.04123933588890878)),
 (4710, np.float64(0.041231138048072935)),
 (1236, np.float64(0.04119107294907994)),
 (690, np.float64(0.04119066818128925)),
 (205, np.float64(0.04114431106962375)),
 (2053, np.float64(0.04110440079595571)),
 (404, np.float64(0.04091428365551541)),
 (79, np.float64(0.04085884963494448)),
 (2417, np.float64(0.04080666538132284)),
 (1307, np.float64(0.04080440595932118)),
 (3606, np.float64(0.040803437174212136)),
 (363, np.float64(0.04076266673964304)),
 (1717, np.float64(0.04075587139721208)),
 (1491, np.float64(0.040641495769810694)),
 (2663, np.float64(0.04061691618121696)),
 (1523, np.float64(0.040483125838390824)),
 (607, np.float64(0.04046135901519456)),
 (775, np.float64(0.04040607492399558)),

In [16]:
# top 5 similarities
movies_indices1 = [tpl[0] for tpl in similarity_scores1[1:6]]
scores_list1 = [f"{round(tpl[1],3)*100}%" for tpl in similarity_scores1[1:6]]
print(movies_indices1)
print(scores_list1)
df["title"].iloc[movies_indices1]

[373, 487, 270, 0, 473]
['29.2%', '24.2%', '22.3%', '21.8%', '21.7%']

373    Mission to Mars
487         Red Planet
270        The Martian
0               Avatar
473      Mars Attacks!
Name: title, dtype: object

# Method-2: using Cosine Similarity with CountVectorizer

In [17]:
similarity_matrix_cs = cosine_similarity(cvt,cvt)
similarity_matrix_cs

array([[1.        , 0.0727393 , 0.05270463, ..., 0.05986843, 0.01937461,
        0.        ],
       [0.0727393 , 1.        , 0.04600437, ..., 0.09798273, 0.        ,
        0.        ],
       [0.05270463, 0.04600437, 1.        , ..., 0.03786412, 0.        ,
        0.        ],
       ...,
       [0.05986843, 0.09798273, 0.03786412, ..., 1.        , 0.06263608,
        0.03966818],
       [0.01937461, 0.        , 0.        , ..., 0.06263608, 1.        ,
        0.05134962],
       [0.        , 0.        , 0.        , ..., 0.03966818, 0.05134962,
        1.        ]], shape=(4803, 4803))

In [18]:
similarity_matrix_cs[0]

array([1.        , 0.0727393 , 0.05270463, ..., 0.05986843, 0.01937461,
       0.        ], shape=(4803,))

### Testing

In [19]:
movie_title = "John Carter"
idx2 = df.loc[df["title"] == movie_title].index[0]
similarity_scores2 = list(enumerate(similarity_matrix_cs[idx2]))
similarity_scores2 = sorted(similarity_scores2, key=lambda x: x[1], reverse=True)

In [20]:
# top 5 similarities
movies_indices2 = [tpl[0] for tpl in similarity_scores2[1:6]]
scores_list2 = [f"{round(tpl[1],3)*100}%" for tpl in similarity_scores2[1:6]]
print(movies_indices2)
print(scores_list2)
df["title"].iloc[movies_indices2]

[373, 0, 260, 270, 581]
['31.900000000000002%', '31.900000000000002%', '28.1%', '28.1%', '27.0%']

373            Mission to Mars
0                       Avatar
260               Ender's Game
270                The Martian
581    Star Trek: Insurrection
Name: title, dtype: object

### Comparison:
- Comparing performance of both algorithms for same input

In [21]:
def get_similar_movies_lk(movie_title):
    idx = df.loc[df["title"] == movie_title].index[0]
    scores = list(enumerate(similarity_matrix_lk[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)

    movies_indices = [tpl[0] for tpl in scores[1:6]]
    similarity_scores = [f"{round(tpl[1],3)*100}%" for tpl in scores[1:6]]

    similar_movie_list = list(df["title"].iloc[movies_indices])
    return similar_movie_list,similarity_scores


def get_similar_movies_cs(movie_title):
    idx = df.loc[df["title"] == movie_title].index[0]
    scores = list(enumerate(similarity_matrix_cs[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)

    movies_indices = [tpl[0] for tpl in scores[1:6]]
    similarity_scores = [f"{round(tpl[1],3)*100}%" for tpl in scores[1:6]]

    similar_movie_list = list(df["title"].iloc[movies_indices])
    return similar_movie_list,similarity_scores

In [24]:
try:
    movie_title = input("Enter your favorite movie: ").strip()
    print("\nTop 5 matches using Linear Kernel:")
    movies, similar = get_similar_movies_lk(movie_title)
    for i, movie in enumerate(movies):
        print("{} --> with {} similarity".format(movie, similar[i]))

    print("\nTop5 matches using Cosine Similarity:")
    movies, similar = get_similar_movies_cs(movie_title)
    for i, movie in enumerate(movies):
        print("{} --> with {} similarity".format(movie, similar[i]))
except IndexError:
    print("No such movie found in the dataset")

Top 5 matches using Linear Kernel:
Aliens --> with 33.7% similarity
Alien³ --> with 30.7% similarity
Mission to Mars --> with 29.9% similarity
Moonraker --> with 27.500000000000004% similarity
Spaceballs --> with 26.900000000000002% similarity

Top5 matches using Cosine Similarity:
Aliens --> with 44.1% similarity
Mission to Mars --> with 42.1% similarity
Alien³ --> with 41.4% similarity
Silent Running --> with 39.2% similarity
Moonraker --> with 38.9% similarity

# Cosine similarity is performing better